backend:
  name: github
  repo: maoydev/FunkyDocs
  branch: main
  base_url: https://sveltia-cms-auth.maoydev-534.workers.dev

media_folder: docs/assets/images
public_folder: /assets/images

collections:
  - name: pages
    label: Pages
    folder: docs
    create: true

    fields:
      - label: Title
        name: title
        widget: string

      - label: Body
        name: body
        widget: richtext
